### PR TITLE
Add explanation of signature endofunctor & initial algebra

### PR DESCRIPTION
**Pull request by jonsterling**
Here's the definition of the signature endofunctor.

Couple questions

1. Do you think I'm playing too fast and loose with notation? (Wasn't sure if "pattern matching" on valences like I did was kosher.)

2. In the definiens, I just sort of "extend" the symbol context by the list of sorts `\vec{p}`, but I don't think I can just do this. I think I need to say, "For any fresh names of `\vec{u}`," and extend the symbol context by `\vec{u}:\vec{p}` or something. Does this sound right? Likewise, something similar might need to be done with the variable context, though instead of names, it's naturals. What do you think?

#15

### CODE REVIEW

**Comment by freebroccolo** [comment]
For (1), I don't see a problem with the notation. In general, I think it's hard to be super precise for this stuff unless you just want to formalize it as a generalized algebraic theory or in some existing framework. But in my opinion, that's what an agda component would be for. Anyway, there is probably a less "pointful" way to express it but I wouldn't worry about it for now.

For (2), I think this is okay. At least, it should be fine for the variable context. If I understand what's going on, it appears to be similar to what I did in the higher-order algebra thing on the way to implementing the induction principle.

As for freshness, I could be wrong but I don't think you usually have to worry about that for the model theoretic or denotational stuff unless you are using the wrong structures somewhere.

**Comment by jonsterling** [comment]
So, the reason I am concerned about (2) is that it seems to be basically a "type error"... `\Upsilon` is collection of symbols and a map from them into sorts, whereas we are extending it by a list of sorts; I am not sure how to construe that as well-defined. This might be an indication that we would want to change the representation of symbol contexts, but I am not certain.

**Comment by freebroccolo** [comment]
Ah, that's a bit clearer to me. This may be similar to defining `++` for `Vec` with the twist that one side is defined as `Fin n -> X` and the other is inductive. I think the way this kind of situation is handled in the literature is that if `Υ = (𝑈, 𝔰)`, you can define an extension of it as `Υ ++ Υ' = (𝑈 ++ 𝑈', [𝔰, 𝔰])`. We don't have another `Υ'`, but if we take `𝑈` to be equivalent to `Fin` then by `|𝑈| + |𝑈'| = m + n` we can just use addition to define `𝑈 ++ 𝑈'` as `Fin (m + n)`. I suppose this would be the same as saying you can produce a collection of `𝑈`-fresh symbols of length `n`, so perhaps your intuition was correct.

The machinery one would need for the `[_,_]` part for `Fin` is [here](https://github.com/freebroccolo/agda-continuous-functions/blob/master/src/Fin.agda#L22-L31).

**Comment by jonsterling** [comment]
@freebroccolo OK, thanks; it sounds like the right thing to do, then, is to add `\prod_{U\in I^n # \Dom{Y}}` or something.

**Pull request merged**
