### PR TITLE
metavariable interpretation

### PR DESCRIPTION
**Pull request by jonsterling**
I went to do the metavariable interpretation, and I realized that we need (I think) to include a collection of symbols to use in the interpretation of the environment.

It also seemed more harmonious to define the substitution monoidal structure's tensor so as to deal with renamings of symbols in addition to substitutions of variables. Do you have any thoughts on whether this is in fact better or worse? I was a little concerned that the previous version, which only varied over variable contexts, did not even give rise to a valid presheaf on `H`, but it is possible my concerns were unfounded.

I have also added some stuff to the agda development:

- updated to reflect changes in paper
- valences & arities
- context concatenation
- the signature endofunctor
- the yoneda embedding
- exponentials of presheaves
- the interpretation of environments

### CODE REVIEW

**Comment by freebroccolo** [comment]
> I went to do the metavariable interpretation, and I realized that we need (I think) to include a collection of symbols to use in the interpretation of the environment.

Okay.

> It also seemed more harmonious to define the substitution monoidal structure's tensor so as to deal with renamings of symbols in addition to substitutions of variables. Do you have any thoughts on whether this is in fact better or worse? I was a little concerned that the previous version, which only varied over variable contexts, did not even give rise to a valid presheaf on H, but it is possible my concerns were unfounded.

I was wondering about this too. I think it would be better to have it deal with both if it doesn't cause any problems. In my experience with these kind of things, going for the more general approach tends to work out better in the long run.

Anyway, the updates look pretty nice.

**Comment by jonsterling** [comment]
So, I've added the inductive definition of the typing judgment to the agda development, and have started trying to translate its derivations to values in the model. The case for variables was simple enough, but I was a little stuck on the case for metavariables. (By the way, I'm not sure that the paper version I've made is totally right, so I'm hoping that we'll figure it out in Agda and then adjust the paper one accordingly.)

**Comment by freebroccolo** [comment]
Nice. As far as the agda definitions for derivations go, you might be able to steal some stuff from my other code. Maybe it is a little clearer what is going on there now. The metavariable case is [here](https://github.com/freebroccolo/higher-order-algebra/blob/master/src/Syntax.agda#L124-L125) followed by explicit substitutions (i.e., what would amount to adding a constructor for the substitution tensor I think) and finally operators. However, I'm using vectors for metavariables and inductive spines for the operator stuff. There's a non-inductive version closer to what we have here in one of the repos I think…

The `[_▹_]_⊧_⇓_` thing is defined [here](https://github.com/freebroccolo/higher-order-algebra/blob/master/src/Syntax.agda#L24-L30) as a kind of natural transformation into a right Kan extension. You can sort of think of it in terms of a CPS style interpreter that works for stuff that requires polymorphic recursion. There's is a simpler example of something similar [here](https://github.com/freebroccolo/hs-algebraic-models/blob/caa9161b6dcd0d8ac986ecee8fc224e2b0062d3d/Main.hs#L176-L180).

**Comment by jonsterling** [comment]
Ah, it's slightly more clear to me now what was going on in your agda code from before!

**Comment by jonsterling** [comment]
I'm going to merge this as well, so that we don't need to maintain a "mega-PR". I'll open tickets for remaining items.

**Pull request merged**
