### PR TITLE
Rearrange semantic universe; start defining interpretation

### PR DESCRIPTION
**Pull request by jonsterling**
When I started defining the interpretation, I realized that it would be easier if I switched semantic universes to a "curried" version of the old one.

@freebroccolo Could you have a look and see if what I've got so far makes sense to you?

#15

### CODE REVIEW

**Comment by freebroccolo** [comment]
I think I will need to study the interpretation stuff described by Fiore more thoroughly in order to be sure I'm really getting it but otherwise it looks good so far.

**Comment by jonsterling** [comment]
Nice changes... Do you think that the alternative presentation you have given can be used to simplify anything (e.g. the definition of substitution)?

**Comment by freebroccolo** [comment]
Possibly. I think it's certainly easier to work with in a type theoretic setting but I haven't really considered how it might change the presentation of the other stuff yet. But since we have described it, I don't see any reason not to use it in specific cases if it turns out to be nicer.

By the way, do you think it might be better to use the notation $f^{v}$ for the extension of $f$? It might be more intuitive but I'm not sure…

**Comment by jonsterling** [comment]
@freebroccolo OK, cool; let's definitely keep it in mind then.

As for the notation, let me first make sure I understand what is meant by extension; is it the extension of a map `P^V` to `P^P`?

**Comment by freebroccolo** [comment]
To elaborate a little, I think we should definitely keep substitution monoidal tensor stuff around. I guess I view this extension operation more in terms of being a useful alias, although I do think the notion of relative monad is pretty fundamental. In order to actually define the extension operation directly you need to have interpretation already implemented and doing that here might make the presentation a little bit awkward even if we could make it work. But maybe I'm wrong about that.

**Comment by jonsterling** [comment]
@freebroccolo OK, thanks for clarifying. Is there something I can read to understand why you need the interpretation already in order to define the extension operation?

**Comment by freebroccolo** [comment]
> As for the notation, let me first make sure I understand what is meant by extension; is it the extension of a map P^V to P^P?

Yes, I believe that is the way to think about it. Concretely, it is just `(=<<)` but for a relative monad.

**Comment by jonsterling** [comment]
OK, thanks. Is there any reason, by the way, that the diagram you drew is not written `P^V --------> P^P`? I wasn't sure I understood the reason for the placeholders in there.

**Comment by freebroccolo** [comment]
> @freebroccolo OK, thanks for clarifying. Is there something I can read to understand why you need the interpretation already in order to define the extension operation?

Actually, come to think of it, that is incorrect. You don't need interpretation already defined, but you do need weakening/renaming. However, if you define these uniformly in terms of interpretation or induction, then it follows that you also need that first for the extension.

This is how I did it in the algebra thing [here](https://github.com/freebroccolo/higher-order-algebra/blob/master/src/Syntax.agda#L113-L144) (`sub` is the extension) but I think Chapman and co usually define the weakening/renaming stuff separately. I dislike their approach a little because it results in several redundant definitions and it tends to get even messier with more complicated term representations.

**Comment by freebroccolo** [comment]
> OK, thanks. Is there any reason, by the way, that the diagram you drew is not written P^V --------> P^P? I wasn't sure I understood the reason for the placeholders in there.

Well, the placeholders are to make it clearer that we have something like `(V A -> P B) -> (P A -> P B)`. It probably would be better to use a pointful style to make that clear but I felt it might clash with the other transformations which weren't written in that way.

**Comment by jonsterling** [comment]
So, unless I'm misunderstanding something, isn't the renaming stuff already present from the fact that these are presheaves on variable contexts (thence, renaming is `map` or whatever)?

It seems like we should be able to define `=<<` in terms of `\nu` and the presheaves' mapping/renaming operation.


-------


Re: the placeholds, aha! I think I understand what's going on then. Thanks!

**Comment by jonsterling** [comment]
I'd be fine with a pointful style, by the way, in that diagram; I think it might make things a bit clearer, even if it is different from the other diagrams.

**Comment by freebroccolo** [comment]
> It seems like we should be able to define =<< in terms of \nu and the presheaves' mapping/renaming operation.

Yes, I think you may be right actually.

**Comment by freebroccolo** [comment]
> I'd be fine with a pointful style, by the way, in that diagram; I think it might make things a bit clearer, even if it is different from the other diagrams.

Okay. Having that one in pointful style sounds good to me.

**Comment by jonsterling** [comment]
> Yes, I think you may be right actually.

Now that I think of it, `\nu` probably wouldn't figure into the definition of the extension; rather, it seems like it should be a composition of `\varsigma` and renaming or something.

**Comment by freebroccolo** [comment]
Regarding notation, I've seen the following in the literature:

- `f\star`
- `f^{*}`
- `f^{#}`

and a few others.

I'm not favor of using `\star` or `*` since they are already way too overloaded in category theory. The current circle star thing might be okay but I think it might be nice to keep that available for something else. What do you think about `f^{#}` or maybe `f^{\sharp}` (see [here](http://arxiv.org/pdf/1205.3050.pdf), page 12 for example)? It seems using an actual symbol is also probably better than using a character.

**Comment by jonsterling** [comment]
@freebroccolo I'm fine with the sharp sign or the pound sign; definitely no to `*` :)

**Comment by freebroccolo** [comment]
Hmm, the way Agda renders the solid circle is super ugly. Maybe there's a better symbol…

**Comment by freebroccolo** [comment]
What do you think about merging this to master? I realize there's more to do on the interpretation stuff still but what's already here seems pretty good.

**Comment by jonsterling** [comment]
Yes, let's merge it in!

**Pull request merged**
