### PR TITLE
Agda refactor

### PR DESCRIPTION
**Pull request by jonsterling**
Opening this PR so that we've got a place to look for and write comments

### CODE REVIEW

**Comment by jonsterling** [comment]
@freebroccolo I'll look at it with this in mind, thanks!

By the way; I've just got four more holes left in the definition of substitution, and they all look "true". So I think we're on the right track!

**Comment by freebroccolo** [comment]
Nice. Looks like it's coming along pretty well. The `aux` parts do look a bit similar to how I had to do weakening for the other code in order to define substitution…

By the way, with the `into` and `out` parts for the abstract types, are these needed in addition to `\iota` and `\pi`? Can we just remove the old ones? The pattern I going for was to just use those names for maps into and out of structures. If the old ones are still needed, maybe we could prefix them with * like some of the other abstract bits.

**Comment by jonsterling** [comment]
@freebroccolo I don't think these do the same thing as `\iota` and `\pi`, do they? At least, they are not interchangeable.

**Comment by jonsterling** [comment]
But I am fine with any proposed renamings :smile:

**Comment by freebroccolo** [comment]
Yeah, they aren't the same. I was just wondering if the old ones were even needed. I saw you use `\pi` but didn't see `\iota`. I didn't actually try to do anything interesting with the abstract parts so I wasn't sure how it would work. I'll have to try out your changes tomorrow.

**Comment by jonsterling** [comment]
Ah, I see what you mean! Yeah, I don't think I've used `iota` anywhere, and my use of `pi` was only in the implementations of `into` and `out`; so feel free to rearrange and rename any of that stuff you like, since I think you have more perspective than I do when it comes to stuff like this.

**Comment by jonsterling** [comment]
By the way, I'm pretty pleased so far with the `abstract` and `no-eta-equality` stuff; definitely a bit of a shock at first, but I don't think I would have been able to make this much progress tonight without it.

**Comment by freebroccolo** [comment]
Cool, glad that seemed to work out. By the way, it is possible to turn off eta globally with a pragma but I prefer to specify it on a per-record basis just in case. Anyway, it is sort of surprising that it helps as much as it does. Kind of wish there was a way to control it in terms of module scope or something but maybe that would be too weird.

**Comment by jonsterling** [comment]
@freebroccolo Do you have any idea how to prove the remaining weakening lemmas? There's four, but they are really just two (duplicated across symbol & variable contexts). I need to show that `Fin.inl` and `Fin.inr` are valid renamings into the concatenation of two contexts.

My initial thought was that I would probably have to do something nasty like encode the graph of `Fin.inl` as a datatype and perform induction on it or something, but I am not sure. Have you proved these lemmas before?

**Comment by freebroccolo** [comment]
@jonsterling I took a look at those and made a brief attempt to implement one of them but didn't push on since it looked like it was going to be more involved than I anticipated. The graph approach might work. I think you can probably do it just by induction on the length of one of the contexts and brute forcing all the cases but that's kind of ugly.

The weakening stuff I proved before looks like this:

For the container version using kan extensions (`f↑*` is precomposition with `f`, `f ↓!` is like \Sigma and `↓*` is like \Pi):
[here](https://github.com/freebroccolo/higher-binding-algebras/blob/master/src/Presheaf.agda#L83-L95)
[here](https://github.com/freebroccolo/higher-binding-algebras/blob/master/src/Presheaf.agda#L158)
[here](https://github.com/freebroccolo/higher-binding-algebras/blob/master/src/Presheaf.agda#L168-L172)

For the version using inductive data:
[here](https://github.com/freebroccolo/higher-order-algebra/blob/master/src/Syntax.agda#L52-L64)
[here](https://github.com/freebroccolo/higher-order-algebra/blob/master/src/Syntax.agda#L120)
[here](https://github.com/freebroccolo/higher-order-algebra/blob/master/src/Syntax.agda#L134-L140)

**Comment by jonsterling** [comment]
Thanks, I'll have a look at your stuff...

New records stuff looks good! By the way, what indentation scheme are you using in those auxiliary functions in the substitution definition?

**Comment by freebroccolo** [comment]
Another idea might be to try to use the `(Fin n -> A) <=> Vec A n` equivalence somehow. I think it would make induction easier at least. May cause other problems though.

**Comment by freebroccolo** [comment]
> By the way, what indentation scheme are you using in those auxiliary functions in the substitution definition?

Hmm, I don't think I had any particular scheme there other than "break lots of lines"… heh :) Feel free to reformat it though.

**Comment by freebroccolo** [comment]
As far as the records stuff goes, I don't know why I didn't do it that way originally. For some reason I convinced myself the other night that records wouldn't work there. Anyway, it's nice that we can use refine and pattern matching again…

**Comment by jonsterling** [comment]
@freebroccolo OK, I'm definitely in favor of lots of line breaks; my preferred scheme is to let the whitespace to the left of the code do all the talking (i.e. the hierarchical structure of the proof tree should be visible by just looking at the left side). :+1: 

Yeah, I like the records stuff too; definitely a bit simpler, and especially good if it seems to preserve the benefits of the other approach.

**Comment by freebroccolo** [comment]
Ah, I see what you mean about indentation and structure now. Yeah, it looks a bit wonky at the moment. I think I screwed up the formatting and didn't notice it. I agree with you about the tree structure thing (that's why those groupoid proofs from the other day looked the way they did).

**Comment by jonsterling** [comment]
@freebroccolo OK, so the interpretation is done, but it's *really* gnarly. You are welcome to make any changes you like! :wink:

**Comment by jonsterling** [comment]
This PR is pointed at the other WIP-interpretation branch rather than master, so I'm going to go ahead and merge it in.

**Comment by freebroccolo** [comment]
Nice! I'll take a look and see if I can figure out some ways to simplify it.

**Pull request merged**
