### PR TITLE
Elaborate a bit on the Grothendieck construction

### PR DESCRIPTION
**Pull request by freebroccolo**

### CODE REVIEW

**Comment by jonsterling** [comment]
Looks good, thanks!

**Comment by jonsterling** [comment]
By the way, is `\pi_O` a fibration or an opfibration?

**Comment by freebroccolo** [comment]
Ah yes, it should be an opfibration.

**Comment by jonsterling** [comment]
BTW, nice bit on the co-end thing; that's quite a clear way to look at it.

**Comment by freebroccolo** [comment]
Thanks :)

**Comment by freebroccolo** [comment]
BTW, I don't really like the name for the projection to pointed sets in the pullback diagram. Do you have any ideas for something better? Seems many of the sources don't even bother to name it.

**Comment by jonsterling** [comment]
@freebroccolo Not sure; sometimes `|_|` can be a nice way to write the stripping of extra information, but I'm not sure if there's precedent since I've not read enough of the literature.

**Comment by jonsterling** [comment]
By the way, can you give me an intuition for what `\pi_\Singleton` does?

**Comment by freebroccolo** [comment]
Sure. So π𝒪 is just the first projection. π{●} should by the functor that takes
∮𝒪 to the category of pointed sets, which (according to nlab) can be understood
as either a set 𝒮 equipped with a chosen element 𝔰 or (by identification of
elements with morphisms) an object of the coslice category {●}/Set.

So I believe the intention is that the functor works like this:

objects:

⟨⟨Υ, ϱ⟩, ϑ⟩ ∈ ∮𝒪 where ϑ ∈ 𝒪⟨Υ , ϱ⟩ map to ! ϑ : {●} → 𝒪⟨Υ , ϱ⟩ ∈ Set

morphisms:

∮𝒪 [⟨⟨Υ , ϱ⟩, ϑ⟩, ⟨⟨Υ′ , ϱ′⟩, ϑ′⟩] where f : ⟨Υ , ϱ⟩ → ⟨Υ′ , ϱ′⟩ such that f* ϑ = ϑ′ ∈ 𝒪⟨Υ′, ϱ′⟩ map to triangles ⟨f* ! ϑ : {●} → 𝒪⟨Υ′ , ϱ′⟩ ∈ Set, ! ϑ′ : {●} → 𝒪⟨Υ′ , ϱ′⟩ ∈ Set⟩ such that f*ϑ {●} = ϑ′ {●} ∈ 𝒪⟨Υ′ , ϱ′⟩ ∈ Set

I think it's something like that anyway…

**Comment by freebroccolo** [comment]
So maybe in that case, assuming it makes sense, it would be reasonable to call it π! ?

**Comment by jonsterling** [comment]
Thanks for the explanation; I think that makes sense. I think `\pi!` is a reasonable notation...

**Comment by freebroccolo** [comment]
Hmm, I just realized that `\pi_{!}` might be confused as somehow being about the left adjoint to substitution, which often written as `f_{!}` (or `Σ_{f}`). Maybe better to just switch it back to bullet (or omit it entirely) but I'll probably leave it for now…

**Pull request merged**
