### PR TITLE
Add a script to render document

### PR DESCRIPTION
**Pull request by freebroccolo**

### CODE REVIEW

**Comment by jonsterling** [comment]
Thanks! I'll merge this by hand...

**Comment by freebroccolo** [comment]
I just fixed it so it should be okay to merge.

**Comment by jonsterling** [comment]
@freebroccolo Looks like we lost your clarifications of the grothendieck stuff... Are you still ok with those changes? I've copied them in locally and am happy to put them in.

**Comment by freebroccolo** [comment]
Yeah, I created a new PR for that.

**Comment by jonsterling** [comment]
Ah, I see the second PR. thanks!

**Pull request merged**
