### PR TITLE
Add definition of substitution monoidal structures & monoid

### PR DESCRIPTION
**Pull request by jonsterling**
@freebroccolo Would you check my work? In generalizing this to our setting, I sort of just guessed what it "had" to be in order to work, but you will likely have a better perspective on this.

#15

### CODE REVIEW

**Comment by freebroccolo** [comment]
Looks good. It makes sense to me the way you've presented it.

**Comment by jonsterling** [comment]
@freebroccolo OK, great! Thanks for having a look :smile: 

Hopefully tonight I'll get around to figuring out how to define the signature endofunctor, which I think might be a tiny bit non-trivial due to the fact that the operator set is fibred over symbol contexts... (It may yet be as trivial as this, but I haven't thought about it yet.)

**Comment by freebroccolo** [comment]
I believe the substitution monoidal structure can also be characterized as a relative monad on the variable presheaf. In other words, `V` serves the role of `J` in the relative monad literature. I haven't seen Fiore mention this but I think It's probably worth pointing out.

**Comment by jonsterling** [comment]
Yes, that sounds right. If a monad is a "monoid in category of endofunctors" (ugh), we should be able to come up with a relative monad from a monoid in the a presheaf category.

**Pull request merged**
